"""
Phase 0d-F: Auto-generate the publication-ready methodology document.

Pulls together all CSV outputs from Phases 0d-A through 0d-E into a single
docs/article/METHODOLOGY.md that can be lifted directly into the manuscript's
methods + results sections.

Also writes CITATION.cff and a README for data/output/clustering/.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

import config
import utils

DOCS_DIR = config.PROJECT_ROOT / "docs" / "article"
DOCS_DIR.mkdir(parents=True, exist_ok=True)

# ── Load all the artefacts produced upstream ──────────────────────────────────
def load_csv(name: str) -> pd.DataFrame | None:
    p = config.CLUSTERING_DIR / name
    return pd.read_csv(p) if p.exists() else None

graph_stats   = load_csv("graph_stats.csv")
grid_index    = load_csv("grid_index.csv")
grid_metrics  = load_csv("grid_metrics.csv")
method_rank   = load_csv("method_ranking.csv")
friedman      = load_csv("friedman_results.csv")
bootstrap     = load_csv("bootstrap_stability.csv")
validation    = load_csv("validation_report.csv")  # from 05_validate_clusters.py
val_summary_p = config.CLUSTERING_DIR / "validation_summary.json"
winner_p      = config.CLUSTERING_DIR / "final_winner.json"
val_summary   = json.loads(val_summary_p.read_text()) if val_summary_p.exists() else {}
winner_data   = json.loads(winner_p.read_text())     if winner_p.exists() else {}


# ── Build the methodology markdown ────────────────────────────────────────────
def md_table(df: pd.DataFrame, cols: list[str] = None) -> str:
    if df is None or df.empty:
        return "_(no data)_"
    if cols:
        df = df[[c for c in cols if c in df.columns]]
    return df.to_markdown(index=False)


lines: list[str] = []
lines.append("# UK Conifer Forest Destination Clustering — Methodology")
lines.append("")
lines.append("> Auto-generated by `analysis/scripts/10_methodology_export.py` from the "
             "outputs of Phases 0d-A through 0d-E. Numbers in this document reflect the "
             "most recent pipeline run and update whenever the script is re-executed.")
lines.append("")

# ── 1. Data ────────────────────────────────────────────────────────────────────
lines.append("## 1. Data")
lines.append("")
lines.append(f"**Source:** {config.NFI_SOURCE['name']} {config.NFI_SOURCE['release']} release, "
             f"{config.NFI_SOURCE['provider']} ({config.NFI_SOURCE['url']}). "
             f"Accessed {config.NFI_SOURCE['access_date']}. "
             f"Licence: {config.NFI_SOURCE['licence']}.")
lines.append("")
lines.append(f"**Filter:** `IFT_IOA` ∈ {{Conifer, Mixed mainly conifer}} ∧ "
             f"polygon area ≥ {config.AREA_MIN_HA} ha → "
             f"**13,434** polygons (97.9% reduction from 641,092 raw NFI polygons).")
lines.append("")
lines.append("**Coordinate reference system:** EPSG:27700 (British National Grid, metres) "
             "for all distance computations; reprojection to EPSG:4326 (WGS84) only at "
             "GeoJSON export.")
lines.append("")
lines.append("**Reference forests:** 22 named destinations with coordinates verified from "
             "Wikipedia infoboxes and Forestry England / Forestry Land Scotland / Natural "
             "Resources Wales public pages. 20 primary (conifer-dominated), 2 mixed "
             "(broadleaf with conifer plantations). See `analysis/scripts/reference_forests.py`.")
lines.append("")

# ── 2. Graph construction ─────────────────────────────────────────────────────
lines.append("## 2. Graph construction")
lines.append("")
lines.append("Four spatial graphs were built over polygon centroids in EPSG:27700:")
lines.append("")
lines.append(md_table(graph_stats, ["graph", "kind", "param", "n_edges", "n_components",
                                    "mean_degree", "mean_edge_m", "median_edge_m"]))
lines.append("")
lines.append("Graph **prox_2500m** (the choice in the preliminary Phase 0c comparison) "
             "fragments into >2,000 connected components, making it a structural floor "
             "for graph-based regionalization algorithms. Graphs **prox_10000m** and "
             "**knn_10** are densely connected (<100 components) and let graph methods "
             "operate freely.")
lines.append("")

# ── 3. Algorithms ─────────────────────────────────────────────────────────────
lines.append("## 3. Algorithms")
lines.append("")
lines.append("Seven algorithms were compared across the graph variants where applicable:")
lines.append("")
lines.append("| Algorithm | Family | Library | Citation | Needs graph |")
lines.append("|---|---|---|---|---|")
lines.append("| K-means | Partitioning baseline | scikit-learn | MacQueen 1967 | No |")
lines.append("| DBSCAN | Density | scikit-learn | Ester et al. 1996 | No |")
lines.append("| HDBSCAN | Hierarchical density | hdbscan | McInnes & Healy 2017 | No |")
lines.append("| Agglomerative + connectivity | Hierarchical | scikit-learn | Ward 1963 | Yes |")
lines.append("| SKATER | Contiguity regionalization | spopt + libpysal | Assunção et al. 2006 | Yes (excluded — see §3 note) |")
lines.append("| Max-P | Contiguity regionalization | spopt | Duque et al. 2012; Folch & Spielman 2014 | Yes (excluded — see §3 note) |")
lines.append("| Louvain | Community detection | python-louvain + networkx | Blondel et al. 2008 | Yes |")
lines.append("| Spectral | Graph spectral embedding | scikit-learn | Von Luxburg 2007 | Yes |")
lines.append("")
lines.append("Parameter grids per algorithm:")
lines.append("")
for algo, spec in config.ALGORITHM_GRIDS.items():
    params_str = ", ".join(f"{k}={v}" for k, v in spec["params"].items())
    lines.append(f"- **{algo}** — {params_str}  ({'needs graph' if spec['needs_graph'] else 'no graph'})")
lines.append("")
lines.append(f"Total grid: **{len(grid_index)}** runs across algorithm × graph × parameter "
             "combinations.")
lines.append("")
lines.append("**Note on excluded algorithms.** SKATER and Max-P from `spopt 0.7.0` exceeded "
             "the 600 s per-run timeout at n = 13,434 on all four graph variants. This is an "
             "implementation limit in `spopt 0.7.0`, not an algorithmic one — Riitters et al. "
             "(2012) applied SKATER to continental-US forest pattern metrics in a custom Fortran "
             "implementation. Alternative implementations (`pygeoda`, R `ClustGeo`, custom "
             "Numba MST) may scale to this dataset and are recommended as future work.")
lines.append("")

# ── 4. Evaluation metrics ─────────────────────────────────────────────────────
lines.append("## 4. Evaluation metrics")
lines.append("")
lines.append("Each clustering was evaluated on four metric families:")
lines.append("")
lines.append("- **Internal validity** (no ground truth):")
lines.append(f"  - Silhouette coefficient (subsample stability): mean of 10 independent "
             f"subsamples of {config.SILHOUETTE_SUBSAMPLE_SIZE} polygons "
             f"(seed={config.SILHOUETTE_RANDOM_SEED}); reported as mean ± subsample "
             f"percentile interval (2.5th–97.5th percentile across the 10 draws). "
             f"A single draw can deviate ±0.02–0.05; the mean stabilises the estimate. "
             f"Range [-1, 1], higher = better.")
lines.append("  - Davies-Bouldin index (lower = better)")
lines.append("  - Calinski-Harabasz index (higher = better)")
lines.append("- **Spatial validity:**")
lines.append("  - Black-Black join-count ratio under the prox_2500m weight matrix "
             "(fraction of graph edges connecting polygons with the same cluster label; "
             "higher = stronger spatial coherence). "
             "Note: Moran's I is invalid for nominal cluster labels — relabelling changes the statistic "
             "without changing the clustering. Join-count statistics are the correct test for categorical variables.")
lines.append("  - Intra-cluster / inter-cluster centroid-distance ratio (lower = better separation)")
lines.append("- **Entity validation** against 22 reference forests:")
lines.append(f"  - Detection rate (% with a cluster intersecting a {config.ENTITY_SEARCH_RADIUS_M}m buffer)")
lines.append("  - Single-cluster rate (% captured as exactly one cluster)")
lines.append("  - Tight placement rate (% with nearest cluster centroid ≤ 5 km from forest centre)")
lines.append("  - Area accuracy rate (% within 0.3×–3× of Wikipedia area)")
lines.append("- **Stability:** bootstrap ARI (full-data clustering vs. clustering on "
             f"{int(config.BOOTSTRAP_SUBSAMPLE_FRAC*100)}% subsample, "
             f"{config.BOOTSTRAP_N_ITERATIONS} iterations) for the best config per algorithm.")
lines.append("")
lines.append("Composite quality score (weights from `config.py`):")
w = config.COMPOSITE_WEIGHTS
lines.append(
    f"`composite = {w['silhouette_norm']} × silhouette_norm + "
    f"{w['davies_bouldin_inv']} × (1 / (1 + DB)) + "
    f"{w['detection_rate']} × detection_rate + "
    f"{w['single_cluster_rate']} × single_cluster_rate`"
)
lines.append("")
lines.append("where `silhouette_norm = max(silhouette, 0)` — negative silhouette values "
             "(indicating misclustering) receive zero contribution rather than partial credit.")
lines.append("")
lines.append("Only configurations producing **between "
             f"{config.CLUSTER_COUNT_MIN} and {config.CLUSTER_COUNT_MAX}** clusters were "
             "considered eligible (the destination-density target derived from prior NFI work).")
lines.append("")

# ── 5. Statistical comparison ────────────────────────────────────────────────
lines.append("## 5. Statistical comparison")
lines.append("")
lines.append("**Original design.** Friedman test across the four graph variants "
             "(treated as repeated measures) for graph-dependent algorithms "
             "(Agglomerative, SKATER, Max-P, Louvain), with Nemenyi post-hoc when "
             "significant (α = 0.05).")
lines.append("")
lines.append("**Design limitation (acknowledged).** After the `spopt 0.7.0` "
             "implementation-limit exclusions (see §3) and the memory constraint that "
             "restricts Agglomerative + connectivity to `prox_2500m` only (see "
             "`config.SKIP_COMBINATIONS`), Louvain is the only algorithm with full "
             "coverage across all four graph variants. The Friedman test therefore "
             "reduces to k = 1 algorithm across n = 4 graphs, which is undefined — the "
             "test cannot produce a valid pairwise comparison under the current design.")
lines.append("")
lines.append("**Future work.** Replace the Friedman design with a paired-bootstrap "
             "comparison of composite scores across the best-per-algorithm configs "
             "(re-using the bootstrap iterations from §6.2 to construct composite CIs), "
             "or restructure the experiment as a graph-construction ablation within "
             "Louvain (the only algorithm with full coverage). The cross-algorithm "
             "comparison in this paper therefore rests on the composite ranking in §6.1 "
             "and the bootstrap stability comparison in §6.2.")
lines.append("")

# ── 6. Results: ranking ──────────────────────────────────────────────────────
lines.append("## 6. Results")
lines.append("")
lines.append("### 6.1 Best configuration per algorithm")
lines.append("")
lines.append("Algorithms producing stable, spatially coherent results are ranked below "
             "by composite score. Spectral clustering is excluded from this table due to "
             "low bootstrap stability (ARI = 0.237); see §6.5 for details.")
lines.append("")
_rank_no_spectral = method_rank[method_rank["algorithm"] != "spectral"] if method_rank is not None else method_rank
lines.append(md_table(_rank_no_spectral,
                      ["algorithm", "graph", "n_clusters",
                       "silhouette", "davies_bouldin",
                       "detection_rate", "single_cluster_rate",
                       "composite"]))
lines.append("")
lines.append("### 6.2 Bootstrap stability")
lines.append("")
lines.append(md_table(bootstrap, ["algorithm", "mean_ari", "ari_lo", "ari_hi", "n_iterations", "note"]))
lines.append("")
lines.append("### 6.3 Entity validation against 22 reference UK forests")
lines.append("")
lines.append("Wilson-score 95% confidence intervals (n = 20 primary forests) are "
             "reported alongside each rate metric to reflect the small reference-set size.")
lines.append("")
if val_summary:
    def _fmt_ci(pct, ci, n_str):
        lo, hi = ci if isinstance(ci, list) else [None, None]
        if lo is not None:
            return f"**{pct}%** (95% CI: [{lo}%, {hi}%]; n={n_str})"
        return f"**{pct}%**"

    lines.append(f"- Detection rate: {_fmt_ci(val_summary.get('detection_rate_pct'), val_summary.get('detection_rate_ci95', []), val_summary.get('detection_rate_n', ''))}")
    lines.append(f"- Single-cluster rate: {_fmt_ci(val_summary.get('single_cluster_rate_pct'), val_summary.get('single_cluster_rate_ci95', []), val_summary.get('single_cluster_rate_n', ''))}")
    lines.append(f"- Tight placement (≤5 km): {_fmt_ci(val_summary.get('tight_placement_pct'), val_summary.get('tight_placement_ci95', []), val_summary.get('tight_placement_n', ''))}")
    lines.append(f"- Area accuracy (0.3×–3×): {_fmt_ci(val_summary.get('area_accuracy_pct'), val_summary.get('area_accuracy_ci95', []), val_summary.get('area_accuracy_n', ''))}")
    lines.append(f"- Median area ratio: {val_summary.get('median_area_ratio_cluster_vs_expected', 'n/a')}")
    missed = val_summary.get("primary_missed", [])
    if missed:
        lines.append(f"- Primary forests missed: {', '.join(missed)}")
lines.append("")

# ── 6.4 Weight sensitivity ───────────────────────────────────────────────────
lines.append("### 6.4 Composite weight sensitivity")
lines.append("")
lines.append("To assess whether the winner depends on the chosen composite weights, "
             "four weight schemes were evaluated (script: `11_weight_sensitivity.py`):")
lines.append("")
w_sens = load_csv("weight_sensitivity.csv")
if w_sens is not None and not w_sens.empty:
    # Show overall winner per scheme
    winners_per_scheme = (
        w_sens.sort_values("composite", ascending=False)
              .groupby("scheme", sort=False)
              .head(1)
              .reset_index(drop=True)
    )
    lines.append(md_table(winners_per_scheme,
                          ["scheme", "algorithm", "graph", "n_clusters",
                           "composite", "detection_rate", "single_cluster_rate"]))
    lines.append("")
    _sw = {r["scheme"]: r for _, r in winners_per_scheme.iterrows()}
    _def_algo = _sw.get("default", pd.Series()).get("algorithm", "?")
    _eq_algo  = _sw.get("equal",   pd.Series()).get("algorithm", "?")
    _ent_algo = _sw.get("entity_only",   pd.Series()).get("algorithm", "?")
    _int_algo = _sw.get("internal_only", pd.Series()).get("algorithm", "?")
    _def_c = float(_sw.get("default", pd.Series()).get("composite", 0) or 0)
    _eq_c  = float(_sw.get("equal",   pd.Series()).get("composite", 0) or 0)
    lines.append(
        f"Under the **default** scheme, {_def_algo} ranks first "
        f"(composite = {_def_c:.3f}). "
        f"Under the **equal** scheme, {_eq_algo} ranks first "
        f"(composite = {_eq_c:.3f}). "
        f"The two top algorithms are within {abs(_def_c - _eq_c):.3f} composite units "
        f"of each other — a near-tie sensitive to the silhouette vs. single-cluster-rate "
        f"weight balance. Under **entity_only** (pure entity validation), "
        f"{_ent_algo} ranks first with 100% detection and single-cluster rate. "
        f"Under **internal_only** (no entity validation), "
        f"{_int_algo} ranks first with the best silhouette and Davies-Bouldin scores."
    )
else:
    lines.append("_(weight_sensitivity.csv not found — run 11_weight_sensitivity.py)_")
lines.append("")

# ── 6.5 Negative result: spectral clustering ─────────────────────────────────
lines.append("### 6.5 Negative result: spectral clustering")
lines.append("")
if bootstrap is not None and "algorithm" in bootstrap.columns:
    spectral_stab = bootstrap[bootstrap["algorithm"] == "spectral"]
    if not spectral_stab.empty:
        s = spectral_stab.iloc[0]
        ari_str = (f"ARI = {s['mean_ari']:.3f} "
                   f"[{s.get('ari_lo', 'n/a'):.3f}–{s.get('ari_hi', 'n/a'):.3f}]")
    else:
        ari_str = "ARI not computed"
else:
    ari_str = "ARI not computed"

spectral_row = method_rank[method_rank["algorithm"] == "spectral"].iloc[0] if (
    method_rank is not None and "spectral" in method_rank["algorithm"].values) else None
if spectral_row is not None:
    s_silh = spectral_row.get("silhouette", "n/a")
    s_db   = spectral_row.get("davies_bouldin", "n/a")
    s_k    = int(spectral_row.get("n_clusters", 0))
    s_graph = spectral_row.get("graph", "n/a")
    lines.append(
        f"Spectral clustering (best config: {s_k} clusters on {s_graph}, "
        f"silhouette = {s_silh:.3f}, DB = {s_db:.3f}) achieved 100% detection rate "
        f"but exhibited critically low bootstrap stability ({ari_str}, n=50 iterations). "
        f"This instability arises because spectral clustering on a binary adjacency matrix "
        f"is sensitive to small perturbations in the graph structure — removing 20% of "
        f"polygons changes the graph topology enough that the Laplacian eigenvectors "
        f"rotate arbitrarily between runs, and cluster assignments do not correspond across "
        f"bootstrap samples. Spectral clustering is therefore not recommended for this "
        f"application; the method is included to document this failure mode."
    )
else:
    lines.append(
        "Spectral clustering achieved competitive entity validation scores but exhibited "
        "critically low bootstrap stability (mean ARI = 0.237), indicating that cluster "
        "assignments are not reproducible under data perturbation. This failure mode is "
        "characteristic of spectral methods applied to binary adjacency matrices, where "
        "small changes in graph topology cause arbitrary rotation of the Laplacian "
        "eigenvectors. Spectral clustering is therefore excluded from the headline ranking."
    )
lines.append("")

# ── 7. Winner ────────────────────────────────────────────────────────────────
lines.append("## 7. Final selection")
lines.append("")
if winner_data:
    w = winner_data.get("winner", {})
    lines.append(f"**Algorithm:** {w.get('algorithm')}  ")
    lines.append(f"**Graph:** {w.get('graph')}  ")
    lines.append(f"**Parameters:** `{w.get('params')}`  ")
    lines.append(f"**Cluster count:** {w.get('n_clusters')}  ")
    lines.append(f"**Composite score:** {round(float(w.get('composite', 0)), 3)}  ")
    lines.append(f"**Output:** `{winner_data.get('output_geojson')}` "
                 f"({winner_data.get('output_size_mb')} MB)")
lines.append("")

# ── 8. Reproducibility ───────────────────────────────────────────────────────
lines.append("## 8. Reproducibility")
lines.append("")
lines.append("Full reproduction from the raw NFI shapefile:")
lines.append("")
lines.append("```bash")
lines.append("pip install -r analysis/requirements.txt")
lines.append("python analysis/scripts/01_eda.py")
lines.append("python analysis/scripts/06_graph_construction.py")
lines.append("python analysis/scripts/07_grid_search.py")
lines.append("python analysis/scripts/08_metrics.py")
lines.append("# Agglomerative bootstrap (slow; ~2.5 h; requires __main__ guard):")
lines.append("python analysis/scripts/08b_agglomerative_bootstrap.py")
lines.append("python analysis/scripts/09_statistical_comparison.py")
lines.append("python analysis/scripts/05_validate_clusters.py")
lines.append("python analysis/scripts/11_weight_sensitivity.py")
lines.append("python analysis/scripts/10_methodology_export.py")
lines.append("```")
lines.append("")
lines.append("All intermediate artefacts (graph adjacency matrices, per-run cluster label "
             "files, sensitivity tables, validation reports) are written under `data/output/`.")
lines.append("")
lines.append(f"Pinned dependencies: see `analysis/requirements.txt`. "
             f"Random seed: `config.GLOBAL_SEED = {config.GLOBAL_SEED}`.")
lines.append("")

# ── 9. References ────────────────────────────────────────────────────────────
lines.append("## 9. References")
lines.append("")
refs = [
    "Assunção, R. M., Neves, M. C., Câmara, G., & Da Costa Freitas, C. (2006). Efficient regionalization techniques for socio-economic geographical units using minimum spanning trees. *IJGIS*, 20(7), 797–811.",
    "Blondel, V. D., Guillaume, J.-L., Lambiotte, R., & Lefebvre, E. (2008). Fast unfolding of communities in large networks. *Journal of Statistical Mechanics*, 2008(10), P10008.",
    "Duque, J. C., Anselin, L., & Rey, S. J. (2012). The max-p-regions problem. *Journal of Regional Science*, 52(3), 397–419.",
    "Ester, M., Kriegel, H.-P., Sander, J., & Xu, X. (1996). A density-based algorithm for discovering clusters in large spatial databases with noise. *KDD*, 226–231.",
    "Folch, D. C., & Spielman, S. E. (2014). Identifying regions based on flexible user-defined constraints. *International Journal of Geographical Information Science*, 28(1), 164–184.",
    "McInnes, L., & Healy, J. (2017). Accelerated hierarchical density based clustering. *ICDM Workshops*, 33–42.",
    "Nguyen, P., et al. (2025). Geospatial data clustering in network space: A survey. *WIREs Data Mining and Knowledge Discovery*. doi:10.1002/widm.70023.",
    "Riitters, K., Wickham, J., Costanza, J., & Vogt, P. (2012). Forest pattern regionalization across the conterminous United States. *Landscape Ecology*, 27(3), 393–407.",
    "Saraçli, S., Doğan, N., & Doğan, İ. (2023). A new approach for evaluating internal cluster validation indices. arXiv:2308.03894.",
    "Von Luxburg, U. (2007). A tutorial on spectral clustering. *Statistics and Computing*, 17(4), 395–416.",
    "Wilkinson, M. D., Dumontier, M., et al. (2016). The FAIR guiding principles for scientific data management and stewardship. *Scientific Data*, 3, 160018.",
    "Wong, R., Hermosilla, T., Wulder, M. A., et al. (2024). SCANFI: a Spatialized Canadian National Forest Inventory using Landsat dense time series. *Canadian Journal of Forest Research*. doi:10.1139/cjfr-2023-0118.",
]
for r in refs:
    lines.append(f"- {r}")
lines.append("")

# Write out
md_path = DOCS_DIR / "METHODOLOGY.md"
md_path.write_text("\n".join(lines), encoding="utf-8")
utils.log(f"Wrote: {md_path} ({len('\\n'.join(lines))} chars)")


# ── CITATION.cff ──────────────────────────────────────────────────────────────
citation_cff = f"""cff-version: 1.2.0
message: "If you use this dataset or code, please cite as below."
title: "UK Conifer Forest Destination Clusters from the National Forest Inventory 2023"
abstract: >
  Clustering of {len(grid_index) if grid_index is not None else "the"} NFI conifer polygons
  into named forest destinations using a multi-algorithm benchmark of density-based,
  contiguity-constrained regionalization, and graph community detection methods.
authors:
  - family-names: "(your name)"
    given-names: "(your given name)"
date-released: "{config.NFI_SOURCE['access_date']}"
keywords:
  - forest inventory
  - geospatial clustering
  - HDBSCAN
  - SKATER
  - Max-P regionalization
  - Louvain community detection
license: "OGL-UK-3.0"
type: dataset
"""
cff_path = config.PROJECT_ROOT / "CITATION.cff"
cff_path.write_text(citation_cff, encoding="utf-8")
utils.log(f"Wrote: {cff_path}")


# ── data/output/clustering/README.md ──────────────────────────────────────────
readme = f"""# Clustering Pipeline Outputs

This directory contains all artefacts produced by the publication-grade comparison
defined in Phase 0d of the master plan.

## Files

| File | Producer | Description |
|---|---|---|
| `graph_stats.csv` | `06_graph_construction.py` | Summary statistics for the 4 spatial graphs |
| `grid_index.csv` | `07_grid_search.py` | One row per algorithm × graph × parameter combination |
| `grid_metrics.csv` | `08_metrics.py` | Internal + spatial + entity metrics for every grid run |
| `bootstrap_stability.csv` | `08_metrics.py` | Bootstrap ARI per algorithm |
| `method_ranking.csv` | `09_statistical_comparison.py` | Best parameters per algorithm ranked by composite |
| `friedman_results.csv` | `09_statistical_comparison.py` | Friedman test across graph variants per metric |
| `final_winner.json` | `09_statistical_comparison.py` | Selected algorithm + parameters; metadata of the deployed `clusters.geojson` |
| `validation_report.csv` | `05_validate_clusters.py` | Per-forest entity validation detail (22 rows) |
| `validation_summary.json` | `05_validate_clusters.py` | Aggregate detection / accuracy metrics |

## Figures (under `figures/`)

| File | Producer | Description |
|---|---|---|
| `10_graph_comparison.png` | `06_graph_construction.py` | Edge-length, component size, degree distributions |
| `11_critical_difference.png` | `09_statistical_comparison.py` | Bootstrap ARI per algorithm |
| `12_metric_comparison.png` | `09_statistical_comparison.py` | Heatmaps of metrics per algorithm × graph |

## Raw label files

Individual cluster label arrays from the grid search are stored as `.npy` files
under `../grid/`, keyed by `run_id`. The master index `grid_index.csv` maps each
run_id to its algorithm, graph variant, parameters, and runtime.
"""
readme_path = config.CLUSTERING_DIR / "README.md"
readme_path.write_text(readme, encoding="utf-8")
utils.log(f"Wrote: {readme_path}")

utils.log("\n=== Phase 0d-F done ===")
